application:
  version: V0.0.1
server:
  port: 6618
spring:
  application:
    name: elasticsearch-data-flow

knife4j:
  enable: true

# Elasticsearch配置
elasticsearch:
  # 源ES配置
  source:
    host: localhost
    port: 9200
    scheme: http
    username: elastic
    password: xxx
  # 目标ES配置
  target:
    host: localhost
    port: 9200
    scheme: http
    username: elastic
    password: xxx
  # 响应缓冲区配置
  response:
    buffer:
      # 响应缓冲区最大限制（字节），调整为1GB以支持百万级数据迁移
      limit: 1073741824  # 1GB
      # 初始缓冲区大小（字节），调整为10MB
      initial: 10485760  # 10MB
  
  # 连接配置 - 优化百万级数据迁移
  connection:
    # 最大总连接数
    max-total: 200
    # 每个路由最大连接数  
    max-per-route: 100
  
  # 超时配置 - 针对大数据量处理优化
  timeout:
    # 连接超时时间（毫秒），增加到30秒
    connect: 30000
    # Socket超时时间（毫秒），增加到10分钟
    socket: 600000
    # 连接请求超时时间（毫秒），增加到1分钟
    connection-request: 60000
  
  # IO线程配置
  io:
    # IO线程数量，0表示使用CPU核数
    thread-count: 0

# ES迁移任务配置
es:
  migration:
    task:
      # 是否启用定时任务
      enabled: false
      # 源索引名称
      source-index: doc-develop
      # 目标索引名称
      target-index: doc-develop2
      # 批次大小 - 针对百万级数据优化，初始设置较大值
      batch-size: 2000
      # 时间戳字段名
      timestamp-field: createTime
      # 忽略大小写的字段（逗号分隔）
      case-insensitive-fields: subject
      # 新增字段（格式：字段名=默认值，逗号分隔）
      new-fields: migration_time=now,migration_version=1.0
      # 字段映射（格式：源字段=目标字段，逗号分隔）
      field-mapping:
    # 断点续传配置
    checkpoint:
      # 断点文件存储目录
      dir: ./checkpoints
      # 是否启用断点续传
      enabled: true
      # 断点保存间隔（处理多少条记录后保存一次断点）
      save-interval: 10000